server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: like-service
  profiles:
    active: mysql
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: error
    org.springframework.web.context.request.async: error

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true

app:
  events:
    exchange: ${APP_EVENTS_EXCHANGE:connectsphere.events}
    notification-routing-key: ${APP_NOTIFICATION_ROUTING_KEY:notification.social}
